import { queryParams, type RouteQueryOptions, type RouteDefinition } from './wayfinder'

/**
 * Custom routes that are not auto-generated by Wayfinder
 */

export const language = (locale: string) => `/language/${locale}`;

export const reports = {
    transactions: {
        url: (options?: any) => {
            const params = new URLSearchParams();
            if (options) {
                Object.entries(options).forEach(([key, value]) => {
                    if (value) params.append(key, String(value));
                });
            }
            const query = params.toString();
            return `/reports/transactions${query ? '?' + query : ''}`;
        },
        pdf: {
            url: (options?: any) => {
                const params = new URLSearchParams();
                if (options) {
                    Object.entries(options).forEach(([key, value]) => {
                        if (value) params.append(key, String(value));
                    });
                }
                const query = params.toString();
                return `/reports/transactions/pdf${query ? '?' + query : ''}`;
            }
        }
    }
};
