import { route } from '@/ziggy';

/**
 * Custom routes that are not auto-generated by Wayfinder
 * or need special parameter handling
 */

export const language = (locale: string) => route('language.switch', { locale });

export const reports = {
    transactions: {
        url: (options?: Record<string, any>) => {
            const params = new URLSearchParams();

            if (options) {
                Object.entries(options).forEach(([key, value]) => {
                    if (value) {
                        params.append(key, String(value));
                    }
                });
            }

            const query = params.toString();

            return `/reports/transactions${query ? '?' + query : ''}`;
        },
        pdf: {
            url: (options?: Record<string, any>) => {
                const params = new URLSearchParams();

                if (options) {
                    Object.entries(options).forEach(([key, value]) => {
                        if (value) {
                            params.append(key, String(value));
                        }
                    });
                }

                const query = params.toString();

                return `/reports/transactions/pdf${query ? '?' + query : ''}`;
            },
        },
    },
};