<?php

namespace App\Http\Controllers;

use App\Services\GroqService;
use App\Services\AnwarLogic;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

class ChatController extends Controller
{
    public function ask(Request $request, GroqService $groqService)
    {
        $request->validate([
            'message' => 'required|string|max:500',
        ]);

        $apiKey = config('services.groq.key') ?? env('GROQ_API_KEY');
        if (!$apiKey) {
            return response()->json(['error' => 'AI Service is not configured.'], 500);
        }

        $user = $request->user();
        
        try {
            // Get the massive context generated by AnwarLogic
            $financialContext = AnwarLogic::getFullFinancialContext($user);
            $contextJson = json_encode($financialContext, JSON_PRETTY_PRINT);
            $creditScore = $user->credit_score;

            $context = "You are SmartBanking AI, an advanced 'What If' Simulation Engine for AtlasPay in Morocco. You are assisting {$user->first_name}.

            YOUR CONTEXT (Real-Time Financial Data):
            - Credit Score: {$creditScore}
            - Data: {$contextJson}

            YOUR MISSION:
            1. The user will ask 'What if...' scenarios (e.g., buying a car, losing salary, saving more).
            2. Simulate the scenario against their current balances, debts, spending behavior, and active goals.
            3. Project the outcome (e.g., 'Your balance will drop to X', 'You will reach your goal 2 months later').
            4. Factor in Moroccan seasonal expenses if relevant (Ramadan, Eid, rentrée scolaire).
            5. Provide personalized, actionable advice based on the simulation.
            6. Auto-detect the language of the user's prompt (Darija, French, English, Arabic) and respond in the same language. Keep the response natural, highly professional but friendly, like a premium financial advisor. Do not output raw JSON, write it as a readable chat message.";

            $answer = $groqService->chat([
                ['role' => 'user', 'content' => $request->message]
            ], $context);

            return response()->json([
                'answer' => $answer
            ]);

        } catch (\Exception $e) {
            Log::error('Chat AI Exception: ' . $e->getMessage());
            return response()->json(['error' => 'Something went wrong on our end.'], 500);
        }
    }
}
