<?php

namespace App\Http\Controllers;

use App\Services\GroqService;
use App\Services\AnwarLogic;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

class ChatController extends Controller
{
    public function ask(Request $request, GroqService $groqService)
    {
        $request->validate([
            'message' => 'required|string|max:500',
        ]);

        $apiKey = config('services.groq.key') ?? env('GROQ_API_KEY');
        if (!$apiKey) {
            return response()->json(['error' => 'AI Service is not configured.'], 500);
        }

        $user = $request->user();
        
        try {
            // Get the massive context generated by AnwarLogic
            $financialContext = AnwarLogic::getFullFinancialContext($user);
            $contextJson = json_encode($financialContext, JSON_PRETTY_PRINT);
            $creditScore = $user->credit_score;

            $context = "You are SmartBanking AI, a friendly financial mentor for AtlasPay in Morocco. You are chatting with {$user->first_name}.

            YOUR CONTEXT (Real-Time Financial Data):
            - Credit Score: {$creditScore}
            - Data: {$contextJson}

            YOUR MISSION:
            1. The user will ask 'What if...' scenarios.
            2. Simulate the outcome internally using the data.
            3. RESPONSE STYLE: Be WARM, FRIENDLY, and BEGINNER-FRIENDLY.
            4. IMPORTANT: Do not show raw math formulas or robotic calculations. Just give the final advice and impact in a natural, conversational way.
            5. Example: Instead of 'X + Y = Z', say 'This might push your travel goal back by 2 months, but you can handle it if you save a bit more on dining.'
            6. Keep it short, direct, but human. No robotic lists.";

            $answer = $groqService->chat([
                ['role' => 'user', 'content' => $request->message]
            ], $context);

            return response()->json([
                'answer' => $answer
            ]);

        } catch (\Exception $e) {
            Log::error('Chat AI Exception: ' . $e->getMessage());
            return response()->json(['error' => 'Something went wrong on our end.'], 500);
        }
    }
}
